version = "1.0"
##
## Git Workspace's Manifest. Please see the documentation at:
##
## https://git-ws.readthedocs.io/en/stable/manual/manifest.html
##


# group-filters = ["-doc", "-feature@path"]
group-filters = []


[[remotes]]
name = "nbiotcloud"
url-base = "git@github.com:nbiotcloud"


[defaults]
revision = "main"
# remote = "nbiotcloud"

[[linkfiles]]
src = "main.code-workspace"
dest = "main.code-workspace"

[[dependencies]]
name = "aligntext"

[[dependencies]]
name = "cocotb-amba"

[[dependencies]]
name = "humannum"

[[dependencies]]
name = "icdutil"

[[dependencies]]
name = "inspectorgadget"

[[dependencies]]
name = "iot-riscv"

[[dependencies]]
name = "makolator"

[[dependencies]]
name = "matchor"

[[dependencies]]
name = "outputfile"

[[dependencies]]
name = "pathutil"

[[dependencies]]
name = "ucdp"

[[dependencies]]
name = "ucdp-addr"

[[dependencies]]
name = "ucdp-amba"

[[dependencies]]
name = "ucdp-common"

[[dependencies]]
name = "ucdp-glbl"

[[dependencies]]
name = "ucdp-ipxact"

[[dependencies]]
name = "ucdp-mem"

[[dependencies]]
name = "ucdp-regf"

[[dependencies]]
name = "ucdp-sv"

[[dependencies]]
name = "uniquer"

[[dependencies]]
name = "test2ref"
