version = "1.0"
##
## Git Workspace's Manifest. Please see the documentation at:
##
## https://git-ws.readthedocs.io/en/latest/manual/manifest.html
##


# group-filters = ["-doc", "-feature@path"]
group-filters = []


# [[remotes]]
# name = "myremote"
# url-base = "https://github.com/myuser"


[defaults]
revision = "main"

[[dependencies]]
name = "aligntext"

[[dependencies]]
name = "humannum"

[[dependencies]]
name = "icdutil"

[[dependencies]]
name = "inspectorgadget"

[[dependencies]]
name = "matchor"

[[dependencies]]
name = "outputfile"

[[dependencies]]
name = "ucdp"

[[dependencies]]
name = "uniquer"

[[dependencies]]
name = "makolator"
